### ISSUE TITLE
[EoDE] Major suggestion: Allow different discord servers to share element lists and configuration.

### ISSUE THREAD

**Issue by FranchuFranchu** [Nv7-GitHub/Nv7Haven#30]
Allow moderators of a Discord server (the "guest" server) to configure the bot to use another server's (the "host" server) element list for users in the guest server. 

Users who joined both servers would have the same inventory. However, moderators in the guest server would not be able to do moderator things in the shared element list such as deleting elements or giving away free elements to people. The guest server would use some of the configuration (`/setpolls`, `/setvotes`) from the host server, but other configuration (`/setvotingchannel`, `/setnewschannel`) would be independent.

There would be many different "privilege levels" for the guest server. They are there to prevent the guest server for making changes to the element list that the host server wouldn't like (pornography, etc). 

- Read only: By default, does not require permission from the host server. Users in this server can join together elements and make new elements for their inventory, but there can be no voting channel in the guest server and they also can't suggest new elements. The guest server can have a news channel.
- Read + Vote: Maybe requires permission from the host server by default? (to prevent guest server bots from voting in the host server element list). Suggestions from the host server are also sent to the guest server's voting channel, where guest users can vote. Votes are shared between them. 
- Read + Vote + Suggest: By default, requires permission from the host server. It is like Read + Vote, but guest users can also suggest new elements and categories like host users can. Suggestions are sent to both server's voting channels.

A read + suggest (but not vote) permission could also be possible.

**How would it work?**

First, a user adds the bot to the guest server. Then, in the host server, a command is executed which shows the host server's ID in the Discord API. The ID could be passed as an argument to a moderator `/setshareserver` command in the guest server's which would ask the host server's administrators for permission to share the element list. 

There are many different ways the host server could be notified of a element list share request, but I think the best one would be a message to a channel where only the bot has write access in (like #news). The moderators could execute a `/accept <guest_server_id>` or `/deny <guest_server_id>` command to either accept or deny the request.

The /setshareserver would also have an extra argument which would be the requested permission level. So, `/setshareserver <server_id> rvs` would request the host server for read + vote + suggest permission on the element list

The host server's administrators can also set an automated permission policy for incoming requests with, say, a `/setshareresponse` command.  It would take a permission (such as R or RVS) and a way to handle it (accept (automatically accept), deny (automatically deny), ask (wait for /accept or /deny command)) as the arguments. 

By default, read only could be `accept` and the rest could be `ask`.

**Why?**
Well, this could allow for more "casual" servers that are focused also having EoDE as a "fun" side bot. Not all server moderators want to turn their whole server into a EoDE-focused server with a very small element list. Having a large element list to start with would be more fun.

 With the Read + Vote + Suggest permission, this would greatly increase the amount of elements being created in element lists and would help EoDE servers have the largest element list for Elemental-like games in the whole world.

**Comment by Nv7-GitHub** [comment]
This doesn't really work with the current architecture of the bot

**Comment by FranchuFranchu** [comment]
Of course, this is a major change after all. 

Firstly, a mapping between guest guilds and host guilds would have to be stored in the database. For the Vote permission, functions like createPoll() and handlePollSuccess() would have to send multiple messages in each call by querying the mapping in reverse and iterating over the guest server's voting/news channels. They would also have to keep track of which messages refer to the same poll, for example by having a mapping between messageIDs in guest servers and messageIDs in the host server (which would have to be stored outside the serverData struct)

Also, guilds would have to be separated from element lists in queries. This could be done by adding another layer of indirection in places like [https://github.com/Nv7-GitHub/Nv7Haven/blob/main/eod/combo.go#L118](eod/combo.go:118) where a mapping of guest guild IDs and host guild IDs could be used to get the element list used by the guest guild.

In places like [https://github.com/Nv7-GitHub/Nv7Haven/blob/main/eod/suggest.go#L27](eod/suggest.go:27) the "suggest" permission would have to be checked.
